# Generated by Django 4.0.4 on 2022-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinformation',
            name='channel',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
