# Generated by Django 4.0.4 on 2022-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='fileId',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
