# Generated by Django 4.0.4 on 2022-06-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_upload_fileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='upload',
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
